//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_GenreFilm
    {
        public string ID { get; set; }
        public string FilmID { get; set; }
        public string GenreFilmID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Genre_film Genre_film { get; set; }
    }
}
