//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Film_GenreFilm = new HashSet<Film_GenreFilm>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string FilmID { get; set; }
        public string FilmName { get; set; }
        public string Author { get; set; }
        public string Producer { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Nation { get; set; }
        public string Description { get; set; }
        public Nullable<double> Rated { get; set; }
        public string Actor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_GenreFilm> Film_GenreFilm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
