//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLRapChieuPhimEntities : DbContext
    {
        public QLRapChieuPhimEntities()
            : base("name=QLRapChieuPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chair> Chairs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Film_GenreFilm> Film_GenreFilm { get; set; }
        public virtual DbSet<Genre_chair> Genre_chair { get; set; }
        public virtual DbSet<Genre_film> Genre_film { get; set; }
        public virtual DbSet<Genre_room> Genre_room { get; set; }
        public virtual DbSet<Projection_room> Projection_room { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
