//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string TicketID { get; set; }
        public string ChairID { get; set; }
        public string FilmID { get; set; }
        public System.DateTime StartTime { get; set; }
        public long Price { get; set; }
        public string UserID { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Film Film { get; set; }
        public virtual User User { get; set; }
    }
}
